namespace RSEM.Other
{
    internal class Enums
    {
        public enum ClassIDs
        {
            CAI_BaseNPC,
            CAK47,
            CBaseAnimating,
            CBaseAnimatingOverlay,
            CBaseAttributableItem,
            CBaseButton,
            CBaseCombatCharacter,
            CBaseCombatWeapon,
            CBaseCSGrenade,
            CBaseCSGrenadeProjectile,
            CBaseDoor,
            CBaseEntity,
            CBaseFlex,
            CBaseGrenade,
            CBaseParticleEntity,
            CBasePlayer,
            CBasePropDoor,
            CBaseTeamObjectiveResource,
            CBaseTempEntity,
            CBaseToggle,
            CBaseTrigger,
            CBaseViewModel,
            CBaseVPhysicsTrigger,
            CBaseWeaponWorldModel,
            CBeam,
            CBeamSpotlight,
            CBoneFollower,
            CBreakableProp,
            CBreakableSurface,
            CC4,
            CCascadeLight,
            CChicken,
            CColorCorrection,
            CColorCorrectionVolume,
            CCSGameRulesProxy,
            CCSPlayer,
            CCSPlayerResource,
            CCSRagdoll,
            CCSTeam,
            CDEagle,
            CDecoyGrenade,
            CDecoyProjectile,
            CDynamicLight,
            CDynamicProp,
            CEconEntity,
            CEconWearable,
            CEmbers,
            CEntityDissolve,
            CEntityFlame,
            CEntityFreezing,
            CEntityParticleTrail,
            CEnvAmbientLight,
            CEnvDetailController,
            CEnvDOFController,
            CEnvParticleScript,
            CEnvProjectedTexture,
            CEnvQuadraticBeam,
            CEnvScreenEffect,
            CEnvScreenOverlay,
            CEnvTonemapController,
            CEnvWind,
            CFEPlayerDecal,
            CFireCrackerBlast,
            CFireSmoke,
            CFireTrail,
            CFish,
            CFlashbang,
            CFogController,
            CFootstepControl,
            CFunc_Dust,
            CFunc_LOD,
            CFuncAreaPortalWindow,
            CFuncBrush,
            CFuncConveyor,
            CFuncLadder,
            CFuncMonitor,
            CFuncMoveLinear,
            CFuncOccluder,
            CFuncReflectiveGlass,
            CFuncRotating,
            CFuncSmokeVolume,
            CFuncTrackTrain,
            CGameRulesProxy,
            CHandleTest,
            CHEGrenade,
            CHostage,
            CHostageCarriableProp,
            CIncendiaryGrenade,
            CInferno,
            CInfoLadderDismount,
            CInfoOverlayAccessor,
            CItem_Healthshot,
            CItemDogtags,
            CKnife,
            CKnifeGG,
            CLightGlow,
            CMaterialModifyControl,
            CMolotovGrenade,
            CMolotovProjectile,
            CMovieDisplay,
            CParticleFire,
            CParticlePerformanceMonitor,
            CParticleSystem,
            CPhysBox,
            CPhysBoxMultiplayer,
            CPhysicsProp,
            CPhysicsPropMultiplayer,
            CPhysMagnet,
            CPlantedC4,
            CPlasma,
            CPlayerResource,
            CPointCamera,
            CPointCommentaryNode,
            CPointWorldText,
            CPoseController,
            CPostProcessController,
            CPrecipitation,
            CPrecipitationBlocker,
            CPredictedViewModel,
            CProp_Hallucination,
            CPropDoorRotating,
            CPropJeep,
            CPropVehicleDriveable,
            CRagdollManager,
            CRagdollProp,
            CRagdollPropAttached,
            CRopeKeyframe,
            CSCAR17,
            CSceneEntity,
            CSensorGrenade,
            CSensorGrenadeProjectile,
            CShadowControl,
            CSlideshowDisplay,
            CSmokeGrenade,
            CSmokeGrenadeProjectile,
            CSmokeStack,
            CSpatialEntity,
            CSpotlightEnd,
            CSprite,
            CSpriteOriented,
            CSpriteTrail,
            CStatueProp,
            CSteamJet,
            CSun,
            CSunlightShadowControl,
            CTeam,
            CTeamplayRoundBasedRulesProxy,
            CTEArmorRicochet,
            CTEBaseBeam,
            CTEBeamEntPoint,
            CTEBeamEnts,
            CTEBeamFollow,
            CTEBeamLaser,
            CTEBeamPoints,
            CTEBeamRing,
            CTEBeamRingPoint,
            CTEBeamSpline,
            CTEBloodSprite,
            CTEBloodStream,
            CTEBreakModel,
            CTEBSPDecal,
            CTEBubbles,
            CTEBubbleTrail,
            CTEClientProjectile,
            CTEDecal,
            CTEDust,
            CTEDynamicLight,
            CTEEffectDispatch,
            CTEEnergySplash,
            CTEExplosion,
            CTEFireBullets,
            CTEFizz,
            CTEFootprintDecal,
            CTEFoundryHelpers,
            CTEGaussExplosion,
            CTEGlowSprite,
            CTEImpact,
            CTEKillPlayerAttachments,
            CTELargeFunnel,
            CTEMetalSparks,
            CTEMuzzleFlash,
            CTEParticleSystem,
            CTEPhysicsProp,
            CTEPlantBomb,
            CTEPlayerAnimEvent,
            CTEPlayerDecal,
            CTEProjectedDecal,
            CTERadioIcon,
            CTEShatterSurface,
            CTEShowLine,
            CTesla,
            CTESmoke,
            CTESparks,
            CTESprite,
            CTESpriteSpray,
            CTest_ProxyToggle_Networkable,
            CTestTraceline,
            CTEWorldDecal,
            CTriggerPlayerMovement,
            CTriggerSoundOperator,
            CVGuiScreen,
            CVoteController,
            CWaterBullet,
            CWaterLODControl,
            CWeaponAug,
            CWeaponAWP,
            CWeaponBaseItem,
            CWeaponBizon,
            CWeaponCSBase,
            CWeaponCSBaseGun,
            CWeaponCycler,
            CWeaponElite,
            CWeaponFamas,
            CWeaponFiveSeven,
            CWeaponG3SG1,
            CWeaponGalil,
            CWeaponGalilAR,
            CWeaponGlock,
            CWeaponHKP2000,
            CWeaponM249,
            CWeaponM3,
            CWeaponM4A1,
            CWeaponMAC10,
            CWeaponMag7,
            CWeaponMP5Navy,
            CWeaponMP7,
            CWeaponMP9,
            CWeaponNegev,
            CWeaponNOVA,
            CWeaponP228,
            CWeaponP250,
            CWeaponP90,
            CWeaponSawedoff,
            CWeaponSCAR20,
            CWeaponScout,
            CWeaponSG550,
            CWeaponSG552,
            CWeaponSG556,
            CWeaponSSG08,
            CWeaponTaser,
            CWeaponTec9,
            CWeaponTMP,
            CWeaponUMP45,
            CWeaponUSP,
            CWeaponXM1014,
            CWorld,
            DustTrail,
            MovieExplosion,
            ParticleSmokeGrenade,
            RocketTrail,
            SmokeTrail,
            SporeExplosion,
            SporeTrail
        }

        public enum MoveType_t
        {
            MOVETYPE_NONE,
            MOVETYPE_ISOMETRIC,
            MOVETYPE_WALK,
            MOVETYPE_STEP,
            MOVETYPE_FLY,
            MOVETYPE_FLYGRAVITY,
            MOVETYPE_VPHYSICS,
            MOVETYPE_PUSH,
            MOVETYPE_NOCLIP,
            MOVETYPE_LADDER,
            MOVETYPE_OBSERVER,
            MOVETYPE_CUSTOM
        }

        public enum GameState
        {
            MENU = 0,
            GAME = 6
        }

        public enum Team
        {
            NONE,
            Spectator,
            Terrorist,
            Counter_Terrorist
        }

        public enum LifeState
        {
            Alive,
            Dead,
            Spectating
        }

        public enum Weapons
        {
            deagle = 1,
            berettas = 2,
            fiveseven = 3,
            glock = 4,
            ak47 = 7,
            aug = 8,
            awp = 9,
            famas = 10,
            g3sg1 = 11,
            galil = 13,
            m249 = 14,
            m4a4 = 16,
            mac10 = 17,
            p90 = 19,
            mp5sd = 23,
            ump = 24,
            xm1014 = 25,
            ppbizon = 26,
            mag7 = 27,
            negev = 28,
            sawedoff = 29,
            tec9 = 30,
            zeus = 31,
            p2000 = 32,
            mp7 = 33,
            mp9 = 34,
            nova = 35,
            p250 = 36,
            scar = 38,
            sg553 = 39,
            ssg = 40,
            m4a1s = 60,
            usp = 61,
            cz75 = 63,
            revolver = 64
        };
    }
}
